"""Cria tabela TbTimes com unique

Revision ID: 8afd57731ba9
Revises: 
Create Date: 2026-09-26 20:50:42.698013

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8afd57731ba9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('TbTimes',
    sa.Column('idTime', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('idSofascore', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('idTime')
    )
    with op.batch_alter_table('TbTimes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_TbTimes_idSofascore'), ['idSofascore'], unique=True)
        batch_op.create_index(batch_op.f('ix_TbTimes_name'), ['name'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('TbTimes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_TbTimes_name'))
        batch_op.drop_index(batch_op.f('ix_TbTimes_idSofascore'))

    op.drop_table('TbTimes')
    # ### end Alembic commands ###
