"""cria tabela TbTimes

Revision ID: 9e2f25c85ce3
Revises: 
Create Date: 2026-09-20 14:52:54.330417

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e2f25c85ce3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('TbTimes',
    sa.Column('idTime', sa.Integer(), nullable=False),
    sa.Column('idSofascore', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('idTime')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('TbTimes')
    # ### end Alembic commands ###
